# Group i18n

### Get language strings [GET /api/i18n/bycode/{code}]

Get i18n json file for selected locale.

+ Parameters
    + code: ua (string) - language code

+ Response 200 (application/json)

    + Body

    {
        "Nothing is found": "Sem resultado",
        "Add Income": "Adicionar Receita",
        "Amount": "Valor",
        "...": "..."
    }