# Group Statistics

### Get Recent Week User Statistics [GET /api/stats/week]

Get recent week user statistics

+ Request (application/json)

    + Attributes (object)
        + utcoffset: (number) - Timezone offset. In hours or minutes. http://momentjs.com/docs/#/manipulating/utc-offset/

    + Headers
            authCode: 421a5bbd0624efebf12b2cbe5454b753

+ Response 200 (application/json)

    + Body

    [ 
        {
            month: 4,
            year: 2016,
            day: 21,
            utcOffset: '-03:00',
            stats:  
            { 
                UAH: 
                { 
                    expense: 0, 
                    profit: 198 
                },
                USD: 
                { 
                    expense: 90, 
                    profit: 11.99 
                }
            } 
        },
        {
            month: 4,
            year: 2016,
            day: 20,
            utcOffset: '-03:00',
            stats:  
            { 
                UAH: 
                { 
                    expense: 0, 
                    profit: 198 
                },
                USD: 
                { 
                    expense: 90, 
                    profit: 11.99 
                }
            } 
        },
        {
            month: 4,
            year: 2016,
            day: 19,
            utcOffset: '-03:00',
            stats:  
            { 
                UAH: 
                { 
                    expense: 0, 
                    profit: 198 
                },
                USD: 
                { 
                    expense: 90, 
                    profit: 11.99 
                }
            } 
        },
        {
            month: 4,
            year: 2016,
            day: 18,
            utcOffset: '-03:00',
            stats:  
            { 
                UAH: 
                { 
                    expense: 0, 
                    profit: 198 
                },
                USD: 
                { 
                    expense: 90, 
                    profit: 11.99 
                }
            } 
        },
        {
            month: 4,
            year: 2016,
            day: 17,
            utcOffset: '-03:00',
            stats:  
            { 
                UAH: 
                { 
                    expense: 0, 
                    profit: 198 
                },
                USD: 
                { 
                    expense: 90, 
                    profit: 11.99 
                }
            } 
        },
        {
            month: 4,
            year: 2016,
            day: 16,
            utcOffset: '-03:00',
            stats:  
            { 
                UAH: 
                { 
                    expense: 0, 
                    profit: 198 
                },
                USD: 
                { 
                    expense: 90, 
                    profit: 11.99 
                }
            } 
        },
        {
            month: 4,
            year: 2016,
            day: 15,
            utcOffset: '-03:00',
            stats:  
            { 
                UAH: 
                { 
                    expense: 0, 
                    profit: 198 
                },
                USD: 
                { 
                    expense: 90, 
                    profit: 11.99 
                }
            } 
        }
    ]


### Get Recent Month User Statistics [GET /api/stats/month]

Get recent month user statistics

+ Request (application/json)

    + Attributes (object)
        + utcoffset: (number) - Timezone offset. In hours or minutes. http://momentjs.com/docs/#/manipulating/utc-offset/
        
    + Headers
            authCode: 421a5bbd0624efebf12b2cbe5454b753

+ Response 200 (application/json)

    + Body

    [ 
        {
            month: 4,
            year: 2016,
            day: 21,
            utcOffset: '-03:00',
            stats:  
            { 
                UAH: 
                { 
                    expense: 0, 
                    profit: 198 
                },
                USD: 
                { 
                    expense: 90, 
                    profit: 11.99 
                }
            } 
        },
        {
            month: 3,
            year: 2016,
            day: 22,
            utcOffset: '-03:00',
            stats:  
            { 
                UAH: 
                { 
                    expense: 0, 
                    profit: 198 
                },
                USD: 
                { 
                    expense: 90, 
                    profit: 11.99 
                }
            } 
        }
    ]



### Get Recent Year User Statistics [GET /api/stats/year]

Get recent year user statistics

+ Request (application/json)

    + Attributes (object)
        + utcoffset: (number) - Timezone offset. In hours or minutes. http://momentjs.com/docs/#/manipulating/utc-offset/
        
    + Headers
            authCode: 421a5bbd0624efebf12b2cbe5454b753

+ Response 200 (application/json)

    + Body

    [ 
        {
            month: 4,
            year: 2016,
            utcOffset: '-03:00',
            stats:  
            { 
                UAH: 
                { 
                    expense: 0, 
                    profit: 198 
                },
                USD: 
                { 
                    expense: 90, 
                    profit: 11.99 
                }
            } 
        },
        {
            month: 2,
            year: 2016,
            utcOffset: '-03:00',
            stats:  
            { 
                UAH: 
                { 
                    expense: 0, 
                    profit: 198 
                },
                USD: 
                { 
                    expense: 90, 
                    profit: 11.99 
                }
            } 
        }
    ]
